name: Docker Build on Feature Branch

on:
  push:
    branches:
      - 'feature/**'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./AM/
        push: false  
        tags: am:${{ github.sha }}